[phases.setup]
nixPkgs = ["...", "nodejs_20", "npm"]

[phases.build]
cmds = [
  "cd backend && npm install",
  "cd frontend && npm install",
  "cd frontend && npm run build"
]

[start]
cmd = "cd backend && npm start"
